### ISSUE TITLE
Error in running EuroSat_Classification.ipynb

### ISSUE THREAD

**Issue by mvanwaveren** [ESA-PhiLab/QNN4EO#1]
Hello,

Thanks a lot for making this repository available.

I am running the notebook
IGARSS2021/EuroSAT_Classification.ipynb

I selected Classes 3 and 4 for the binary classification.

When I get to the step
"2. Traing the QNN4EO model"

I get the following error message:
"Simulation failed and returned the following error message:
ERROR: Failed to load qobj: [json.exception.type_error.302] type must be array, but is number"

This error comes from 
`job = qiskit.execute((self._circuit,
                            self.backend, 
                            shots = self.shots,
                            parameter_binds = [{self.theta: theta} for theta in thetas])`

in the method `run` of `QuantumCircuit.`

Can you let me know what I should do to fix this?

Regards,
Matthijs van Waveren

**Comment by alessandrosebastianelli** [comment]
Hi,
probably it depends on the version of the qiskit library. I had a similar issue in the past.

Please try to uninstall your current version of qiskit and reinstall it with this command:
!pip install qiskit==0.23.0

**Comment by mvanwaveren** [comment]
Thank you, installing a previous version of `qiskit `solves the problem!

For future readers:
When you uninstall `qiskit`,  you need to manually uninstall all `qiskit `related packages.

```
pip uninstall qiskit 
pip uninstall qiskit-aer 
pip uninstall qiskit-aqua 
pip uninstall qiskit-ibmq-provider
pip uninstall qiskit-ignis
pip uninstall qiskit-terra 
```

When you install `qiskit `v0.23.0, `pip `installs automatically all qiskit related packages. `pip `however cannot uninstall these packages automatically. This is an issue with `pip`.

**Comment by mvanwaveren** [comment]
..
